#!/usr/bin/ruby --disable-gems

require 'pathname'

file_path = Pathname.new(__FILE__).realpath
gems_setup = File.expand_path('../../vendor/gems/setup.rb', file_path)

require gems_setup

$LOAD_PATH.unshift(File.expand_path('../../rubylib', file_path))

require 'marooned'

begin
  Marooned::CLI.new(ARGV).run
rescue MaroonedException => e
  puts e.message
  exit 1
end
